-- DROP DATABASE IF EXISTS escape_room;
CREATE DATABASE IF NOT EXISTS escape_room;
USE escape_room;

CREATE TABLE escape_room (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE room (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  theme ENUM ('MYSTERY', 'FANTASY', 'SCIFI'),
  difficulty_level ENUM ('EASY', 'MEDIUM', 'HARD') NOT NULL,
  price DOUBLE NOT NULL,
  escape_room_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_room_escape_room_id FOREIGN KEY (escape_room_id) REFERENCES escape_room (id) ON DELETE SET NULL
);

CREATE TABLE clue (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  theme ENUM ('MYSTERY', 'FANTASY', 'SCIFI') NOT NULL,
  price DOUBLE NOT NULL,
  room_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_clue_room_id FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE
);

CREATE TABLE decoration (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  material VARCHAR(255) NOT NULL,
  price DOUBLE NOT NULL,
  room_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_decoration_room_id FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE
);

CREATE TABLE player (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  subscriber BOOLEAN NOT NULL DEFAULT false,
  escape_room_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_player_escape_room_id FOREIGN KEY (escape_room_id) REFERENCES escape_room (id) ON DELETE SET NULL
);

CREATE TABLE player_has_room (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  room_id INT NOT NULL,
  player_id INT NOT NULL,
  is_solved BOOLEAN NOT NULL DEFAULT false,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_player_room UNIQUE (room_id, player_id),
  CONSTRAINT fk_player_room_player_id FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE,
  CONSTRAINT fk_player_room_room_id FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE
);

CREATE TABLE tickets (
    id INT PRIMARY KEY AUTO_INCREMENT,
    room_id INT,
    player_id INT,
    total_price DOUBLE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (room_id) REFERENCES room(id) ON DELETE SET NULL,
    FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE SET NULL
);

drop table escape_room;